import random

def show_rules() -> None:
    """This function allows user to read the rules of the game"""

    print("-"*15)

    print("Welcome to my Bulls and Cows console game!\n"
          "Bulls and Cows is a code-breaking game where you try to guess a secret 4-digit "
          "number with unique digits generated by the computer.\nAfter each guess, you "
          "receive feedback in two values: "
          "\n- Bulls mean correct digits in the correct position 🐂"
          "\n- Cows mean correct digits placed in the wrong position 🐄"
          "\nFor example, if the secret number is 3914 and you guess 1954, you get 2 Bulls for 9 and 4, "
          "\nand 1 Cow for 1. "
          "\nYou win the game when you get 4 Bulls.")

    print("-"*15)

def menu() -> None:
    """This function opens up a menu with different options a user can choose from"""

    while True:
        print("1. Start a new game \n"
              "2. Read the rules \n"
              "3. Exit")

        match input("Your move: "):
            case "1":
                start_game()
            case "2":
                show_rules()
            case "3":
                break

def check_for_bulls(target_number: list[int], user_guess: list[int]) -> int:
    """This function counts how many bulls there are in a user's guess"""

    bulls_count = 0

    for i in range(len(user_guess)):
        if target_number[i] == user_guess[i]:
            bulls_count += 1

    return bulls_count

def check_for_cows(target_number: list[int], user_guess: list[int]) -> int:
    """This function counts how many cows there are in a user's guess"""

    cows_count = 0

    for i in range(len(user_guess)):
            if user_guess[i] in target_number and not target_number[i] == user_guess[i]:
                cows_count += 1

    return cows_count

def call_victory_menu(guessed_number: list[int]) -> None:
    """This function appears when a user wins. It shows a victory message."""

    target_str = "".join(map(str, guessed_number))
    print(f"Congratulations! Your guess was correct! The target number was indeed {target_str}\n")

def make_user_guess() -> list[int]:
    """This function asks user to take a guess"""

    user_guess = input("Your guess: ")

    while True:
        if not len(user_guess) == 4 or not user_guess.isdigit():
            print("Wrong input! Your guess must be a 4-digit number. Try again!")
            user_guess = input("Your guess: ")
        elif len(set(user_guess)) != 4:
            print("Digits must be unique! Try again!")
            user_guess = input("Your guess: ")
        else:
            break

    return list(map(int, list(user_guess)))


def start_game() -> None:
    """This function allows user to start a game"""

    target_number = random.sample(range(10), 4)

    print("The computer made its choice!")

    while True:
        user_guess = make_user_guess()

        bulls_count = check_for_bulls(target_number, user_guess)
        cows_count = check_for_cows(target_number, user_guess)

        if bulls_count == 4:
            break
        else:
            print(f"You got: \n {bulls_count} bulls; \n {cows_count} cows.")

    call_victory_menu(target_number)

menu()