import random


def show_rules() -> None:
    """This function allows user to read the rules of the game"""

    print("-" * 15)

    print(
        "Welcome to my Bulls and Cows console game!\n"
        "Bulls and Cows is a code-breaking game where you try to guess a secret 4-digit "
        "number with unique digits generated by the computer.\nAfter each guess, you "
        "receive feedback in two values: "
        "\n- Bulls mean correct digits in the correct position 🐂"
        "\n- Cows mean correct digits placed in the wrong position 🐄"
        "\nFor example, if the secret number is 3914 and you guess 1954, you get 2 Bulls for 9 and 4, "
        "\nand 1 Cow for 1. "
        "\nYou win the game when you get 4 Bulls."
    )

    print("-" * 15)


def menu() -> int | None:
    """This function opens up a menu with different options a user can choose from"""
    game_difficulty = 2
    previous_moves_switch = True

    while True:
        print("1. Start a new game \n"
            "2. Read the rules \n"
            "3. Change game difficulty\n"
            "4. Manage display\n"
            "5. Exit")


        match input("Your move: "):
            case "1":
                start_game(game_difficulty, previous_moves_switch)
            case "2":
                show_rules()
            case "3":
                game_difficulty = choose_game_difficulty()
                match game_difficulty:
                    case 1:
                        print("Game difficulty changed to Easy (3-digit)")
                    case 2:
                        print("Game difficulty changed to Standard (4-digit)")
                    case 3:
                        print("Game difficulty changed to Hardcore (5-digit)")
            case "4":
                if previous_moves_switch:
                    print("Would you like to hide your previous moves?")
                    print("1. Yes\n2. No")
                    if input() == "1":
                        previous_moves_switch = False
                    else:
                        continue
                else:
                    print("Would you like to show your previous moves?")
                    print("1. Yes\n2. No")
                    if input() == "1":
                        previous_moves_switch = True
                    else:
                        continue
            case "5":
                break
            case _:
                continue


def choose_game_difficulty() -> int:
    print("What difficulty would you like to play?")
    print("1. Easy (3-digit number)\n2. Standard (4-digit number)\n3. Hardcore (5-digit number)")
    match input():
        case "1":
            return 1
        case "2":
            return 2
        case "3":
            return 3
        case _:
            return 2


def check_for_bulls(target_number: list[int], user_guess: list[int]) -> int:
    """This function counts how many bulls there are in a user's guess"""

    bulls_count = 0

    for i in range(len(user_guess)):
        if target_number[i] == user_guess[i]:
            bulls_count += 1

    return bulls_count


def check_for_cows(target_number: list[int], user_guess: list[int]) -> int:
    """This function counts how many cows there are in a user's guess"""

    cows_count = 0

    for i in range(len(user_guess)):
        if (
            user_guess[i] in target_number
            and not target_number[i] == user_guess[i]
        ):
            cows_count += 1

    return cows_count


def call_victory_menu(guessed_number: list[int], moves: int) -> None:
    """This function appears when a user wins. It shows a victory message."""

    target_str = "".join(map(str, guessed_number))
    print(f"Congratulations! Your guess was correct! The target number was indeed {target_str}")

    if moves == 1:
        print(f"It took you {moves} move to guess this number\n")
    else:
        print(f"It took you {moves} moves to guess this number\n")


def make_user_guess(difficulty: int | None) -> list[int]:
    """This function asks user to take a guess"""

    target_len = 4

    if difficulty == 1:
        target_len = 3
    elif difficulty == 2:
        target_len = 4
    elif difficulty == 3:
        target_len = 5

    while True:
        user_guess = input("Your guess: ")

        if not len(user_guess) == target_len or not user_guess.isdigit():
            print(f"Wrong input! Your guess must be a {target_len}-digit number. Try again!")
        elif len(set(user_guess)) != target_len:
            print("Digits must be unique! Try again!")
        else:
            break

    return list(map(int, list(user_guess)))


def start_game(difficulty: int | None = None, show_prev_moves: bool = True) -> None:
    """This function allows user to start a game"""
    match difficulty:
        case 1:
            target_number = random.sample(range(10), 3)
        case 3:
            target_number = random.sample(range(10), 5)
        case _:
            target_number = random.sample(range(10), 4)

    moves_counter = 0
    surrender = False
    previous_moves = {}

    print("The computer made its choice!")

    while True:
        user_guess = make_user_guess(difficulty)

        bulls_count = check_for_bulls(target_number, user_guess)
        cows_count = check_for_cows(target_number, user_guess)

        if bulls_count == len(target_number):
            moves_counter += 1
            break
        else:
            print(f"You got: \n{bulls_count} bulls; \n{cows_count} cows.")
            moves_counter += 1

            if show_prev_moves:
                user_guess_str = "".join(map(str, user_guess))
                previous_moves[user_guess_str] = f"{bulls_count} bulls, {cows_count} cows"

                print("-" * 10)

                print("Your previous moves:")

                for key, value in previous_moves.items():
                    print(f"{key}: {value}")

                print("-" * 10)

        if moves_counter % 5 == 0:
            print(f"You have already made {moves_counter} moves. Would you like to surrender?")
            print("1. Continue game \n2. Surrender")
            match input():
                case "1":
                    continue
                case "2":
                    target_str = "".join(map(str, target_number))
                    surrender = True
                    print(f"You were close enough! The guessed number was {target_str}\n")
                    break
                case _:
                    pass

    if not surrender:
        call_victory_menu(target_number, moves_counter)

menu()